### ISSUE TITLE
Add missing relations

### ISSUE THREAD

**Issue by jdegoes** [paf31/purescript-leibniz#2]
Inspired by [this discussion](https://www.reddit.com/r/purescript/comments/4x1jq3/approximating_gadts_in_purescript/).

``` purescript
trans :: forall a b c. a ~ b -> b ~ c -> a ~ c
```

Also, generalizing the higher-kinded lower functions:

``` purescript
lowerLeibniz2' :: forall f a b c d. f a b ~ f c d -> Tuple (a ~ c) (b ~ d)
```

e.g. for `f` that is `Tuple`, `Either`, etc., and so on.

**Comment by paf31** [comment]
`trans` is just `>>>` from `Category` 😄 

I'll add the other one.
