### ISSUE TITLE
`inner` and `outer`

### ISSUE THREAD

**Issue by rgrempel** [paf31/purescript-leibniz#9]
In [some code](https://github.com/rgrempel/purescript-elm-compat/blob/859a0812bf7e8a4b7dc45b169371786cd1ffcb3d/src/Elm/Json/Decode.purs#L194-L202) I was working on, I needed (wanted?) to define these two functions:

```purs
inner :: ∀ f g a b. (f a ~ g b) -> (a ~ b)
inner _ = Leibniz unsafeCoerce

outer :: ∀ f g a b c. (f a ~ g b) -> (f c ~ g c)
outer _ = Leibniz unsafeCoerce
```

(In fact, I only really needed `inner`). These are like `lowerLeibniz` and `liftLeibniz`, except that the type signature is a bit relaxed -- e.g. `lowerLeibniz` more strictly requires `(f a ~ f b) -> (a ~ b)`, where the constructors must match.

The implementation of `inner` and `outer` are, of course, trivial (in one sense) -- the question is whether it is justified. (That is, whether the `unsafeCoerce` is a shortcut for a conclusion we are justified in reaching).

The [Haskell version](https://hackage.haskell.org/package/eq-4.2/docs/Data-Eq-Type.html) of the Leibniz library does limit itself to `f a ~ f b -> a ~ b` ... that is, the constructors must match, so that may mean there is a problem with my `inner`.

However, the [Haskell GADT library](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Type-Equality.html) defines exactly my `inner` and `outer` (well, I translated `outer` a bit in the absence of polykinds).

Of course, that could be due to some advantage which GADTs have over Leibniz equality. However, [Sulzmann and Wang's paper](https://www.cs.ox.ac.uk/files/3060/gadtless.pdf) "GADTless Programming in Haskell 98" has a discussion of what amounts to `inner` at pp. 12-13. In fact, at the bottom of p. 12, it states [my particular use-case](https://github.com/rgrempel/purescript-elm-compat/blob/859a0812bf7e8a4b7dc45b169371786cd1ffcb3d/src/Elm/Json/Decode.purs#L585-L602) fairly precisely -- that is, I have two types in which I've "forgotten" both the constructor and the type it is applied to, but I know they are both equal to a third type.

> The second two last function clauses are interesting. The patterns of the
> first and second argument constrain k to Either k1 k2 and Either k1’ k2’,
> respectively. Hence, we have
>
>     Either k1 k2 = k = Either k1'  k2'
>
> from which we can follow k1 = k1' and k2 = k2'

If I'm following Sulzmann and Wang's discussion at the top of p. 13 correctly, they are saying that you can't implement `inner` with a `newtype` approach, but you can do it with a (less efficient) series of explicit coercions (they give more details in their Appendix A). I can't say I actually follow the discussion entirely, but it seems as though they are arguing that something like `inner` is correctly definable (in Haskell 98). In a sense, it's just that conclusion that matters for our purposes, since it's trivially definable with `unsafeCoerce` ... it's just a question of whether it justifiable to take that shortcut, and I think they are arguing that it is.

Anyway, what I'm suggesting is that perhaps `inner` and `outer` could be added here (or, one could relax the type signatures for `liftLeibniz` and `lowerLeibniz`). But, of course, that depends on a judgment that the inference they would express is indeed sound.

**Comment by rgrempel** [comment]
Ah, I've just noticed that the example I referred to on p. 12 isn't quite like my use-case after all ... it's more like `lowerLeibniz1of2` and `lowerLeibniz2of2` ... I'll ponder that a bit.

**Comment by paf31** [comment]
I've thought about this a bit, and I can't think of any reason why either of `inner` or `outer` should be unsafe, since we never reduce any type applications other than type synonyms, which can't be partially applied anyway.

Do you have time to put together a PR (ideally against my existing 0.12 branch) please?

**Comment by rgrempel** [comment]
Sure, I'd be happy to do that, sometime in the next few days.

**Comment by rgrempel** [comment]
In constructing PR #10, I ended up modifying the `lowerLeibniz` variants rather than creating a separate `inner` ... it seemed to make more sense to do that, since existing code which used `lowerLeibniz` would continue to work.

I also took a look at the relationship between `outer` and `liftLeibniz`. They don't relate as neatly, because the `liftLeibniz` variations don't ask for any evidence that lets us infer the equality of two distinct type constructors. So, we can't just relax the signatures for `liftLeibniz` ... we need something a little different.

The Haskell GADT library doesn't have something exactly like `liftLeibniz` -- instead, it has `outer` and `apply`, defined like this.

```haskell
apply :: (f :~: g) -> (a :~: b) -> f a :~: g b
outer :: (f a :~: g b) -> f :~: g
```

Now, if you're lifting `a ~ b` over type constructor `f` (i.e. something like `liftLeibniz`), then I suppose it's really `apply` that you would use in the Haskell library (since you can trivially get evidence that `f ~ f`). So, the role of `outer` is partly to get evidence to pass to `apply`, in the non-trivial cases. And, of course, in Haskell they have polykinds, so they don't need multiple variants of these things.

What this makes me wonder is whether just having `outer` might not be enough ... perhaps we actually need a version of `apply` as well?

So, something like:

```purs
-- | Apply an equality of type constructors to an equality of arguments.
applyLeibniz :: forall f g a b c d. f a ~ g b -> c ~ d -> f c ~ g d
applyLeibniz _ _ = Leibniz unsafeCoerce

-- In which case, the existing `liftLeibniz` could be implemented in this way,
-- since we can trivially provide evidence that `f x ~ f x`, using `identity`
liftLeibniz :: forall f a b. a ~ b -> f a ~ f b
liftLeibniz = applyLeibniz identity
```

Though, of course, we don't have polykinds, so I believe we'd need multiple variations of `applyLeibniz` to match the variations of `liftLeibniz`.

I suppose we could change the definitions of all the `liftLeibniz` variations in a manner similar to the `applyLeibniz` signature above. This wouldn't be backwards-compatible, but we could document that for existing uses of `liftLeibniz proof` you'd just have to say `liftLeibniz identity proof` instead. (The advantage of this over a separate `applyLeibniz` is to avoid having two sets of polykind variants).

And, I suppose if we have it defined this way, we don't really need a separate `outer`. (That is, in Haskell, it's polykinds that make it sensible to have a separate `outer` and `apply` ... without polykinds, it seems to make more sense to combine them).

Anyway, perhaps I'll try a separate PR for that ... #10 is limited to the `lowerLeibniz` variants.

**Comment by rgrempel** [comment]
I've added a second PR, #11, which implements `applyLeibniz` and its variously-kinded variants. I didn't change the signature for `liftLeibniz` and variants, because the type signatures for the variants of `applyLeibniz` become a bit verbose (so retaining the simpler forms as well seems sensible).
